### ISSUE TITLE
README.md is outdated.

### ISSUE THREAD

**Issue by Zxun2** [AY2223S2-CS2103T-W12-1/tp#15]
Update the current readme to better reflect the application, value proposition and target audience.

**Comment by gohyongjing** [comment]
To do:
* Add a UI mockup of your intended final product. Note that the image of the UI should be named docs/images/Ui.png. Limit the file to contain one screenshot/mockup only and ensure the new image is roughly the same height x width proportions as the original one.
 If we did the above update correctly, UI mock up and profile photos should appear in your project website and this [Project List Page](https://nus-cs2103-ay2223s2.github.io/website/admin/teamList.html).
* Update all contents to match our project.
* Update the link of the GitHub Actions build status badge (Build Status) so that it reflects the build status of your team repo.
* Acknowledge the original source of the code e.g.,
`This project is based on the AddressBook-Level3 project created by the [SE-EDU initiative](https://se-education.org).`
